name: rolo_app


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2
  cupertino_icons: ^1.0.2

  # Add your dependencies here

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/explorer.png
  #fonts:
  #  - family: Schyler
  #    fonts:
  #      - asset: fonts/Schyler-Regular.ttf
  #      - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
dev_dependencies:
  flutter_test:
    sdk: flutter

